general.import = [
  "/home/gwallgof/.config/colorschemes/kanagawa/alacritty/kanagawa.toml"
]

[font]
size = 11.0

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

[window]
opacity = 0.8
